AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.

Resources:
# HelloWorld Function
  helloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Provided
      Runtime: provided
      CodeUri: .build/lambda/HelloWorld/lambda.zip
# Instructs new versions to be published to an alias named "live".
      AutoPublishAlias: live
