//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftAWSLambdaRuntime open source project
//
// Copyright (c) 2020 Apple Inc. and the SwiftAWSLambdaRuntime project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftAWSLambdaRuntime project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

#if !canImport(ObjectiveC)
import XCTest

extension LambdaTestingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LambdaTestingTests = [
        ("testAsyncLongRunning", testAsyncLongRunning),
        ("testCodableClosure", testCodableClosure),
        ("testCodableVoidClosure", testCodableVoidClosure),
        ("testConfigValues", testConfigValues),
        ("testEventLoopLambdaHandler", testEventLoopLambdaHandler),
        ("testFailure", testFailure),
        ("testLambdaHandler", testLambdaHandler),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LambdaTestingTests.__allTests__LambdaTestingTests),
    ]
}
#endif
