//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftAWSLambdaRuntime open source project
//
// Copyright (c) 2020 Apple Inc. and the SwiftAWSLambdaRuntime project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftAWSLambdaRuntime project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

#if !canImport(ObjectiveC)
import XCTest

extension ALBTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ALBTests = [
        ("testRequestWithSingleValueHeadersEvent", testRequestWithSingleValueHeadersEvent),
    ]
}

extension APIGatewayTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APIGatewayTests = [
        ("testRequestDecodingExampleGetRequest", testRequestDecodingExampleGetRequest),
        ("testRequestDecodingTodoPostRequest", testRequestDecodingTodoPostRequest),
        ("testResponseEncoding", testResponseEncoding),
    ]
}

extension APIGatewayV2Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APIGatewayV2Tests = [
        ("testRequestDecodingExampleGetRequest", testRequestDecodingExampleGetRequest),
    ]
}

extension Base64Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Base64Tests = [
        ("testBase64DecodingAllTheBytesSequentially", testBase64DecodingAllTheBytesSequentially),
        ("testBase64DecodingArrayOfNulls", testBase64DecodingArrayOfNulls),
        ("testBase64DecodingWithInvalidLength", testBase64DecodingWithInvalidLength),
        ("testBase64DecodingWithPoop", testBase64DecodingWithPoop),
        ("testBase64UrlDecodingAllTheBytesSequentially", testBase64UrlDecodingAllTheBytesSequentially),
        ("testDecodeEmptyString", testDecodeEmptyString),
        ("testNSStringToDecode", testNSStringToDecode),
    ]
}

extension CloudwatchTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CloudwatchTests = [
        ("testCustomEventFromJSON", testCustomEventFromJSON),
        ("testEC2InstanceStateChangeNotificationEventFromJSON", testEC2InstanceStateChangeNotificationEventFromJSON),
        ("testEC2SpotInstanceInterruptionNoticeEventFromJSON", testEC2SpotInstanceInterruptionNoticeEventFromJSON),
        ("testScheduledEventFromJSON", testScheduledEventFromJSON),
        ("testTypeMismatch", testTypeMismatch),
        ("testUnregistredType", testUnregistredType),
    ]
}

extension DateWrapperTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DateWrapperTests = [
        ("testISO8601CodingWrapperFailure", testISO8601CodingWrapperFailure),
        ("testISO8601CodingWrapperSuccess", testISO8601CodingWrapperSuccess),
        ("testISO8601WithFractionalSecondsCodingWrapperFailure", testISO8601WithFractionalSecondsCodingWrapperFailure),
        ("testISO8601WithFractionalSecondsCodingWrapperSuccess", testISO8601WithFractionalSecondsCodingWrapperSuccess),
        ("testRFC5322DateTimeCodingWrapperFailure", testRFC5322DateTimeCodingWrapperFailure),
        ("testRFC5322DateTimeCodingWrapperSuccess", testRFC5322DateTimeCodingWrapperSuccess),
        ("testRFC5322DateTimeCodingWrapperWithAlphabeticTimeZoneSuccess", testRFC5322DateTimeCodingWrapperWithAlphabeticTimeZoneSuccess),
        ("testRFC5322DateTimeCodingWrapperWithExtraTimeZoneSuccess", testRFC5322DateTimeCodingWrapperWithExtraTimeZoneSuccess),
    ]
}

extension DynamoDBTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DynamoDBTests = [
        ("testAttributeValueBinaryDecoding", testAttributeValueBinaryDecoding),
        ("testAttributeValueBinarySetDecoding", testAttributeValueBinarySetDecoding),
        ("testAttributeValueBoolDecoding", testAttributeValueBoolDecoding),
        ("testAttributeValueEmptyDecoding", testAttributeValueEmptyDecoding),
        ("testAttributeValueEquatable", testAttributeValueEquatable),
        ("testAttributeValueListDecoding", testAttributeValueListDecoding),
        ("testAttributeValueMapDecoding", testAttributeValueMapDecoding),
        ("testAttributeValueNullDecoding", testAttributeValueNullDecoding),
        ("testAttributeValueNumberDecoding", testAttributeValueNumberDecoding),
        ("testAttributeValueNumberSetDecoding", testAttributeValueNumberSetDecoding),
        ("testAttributeValueStringDecoding", testAttributeValueStringDecoding),
        ("testAttributeValueStringSetDecoding", testAttributeValueStringSetDecoding),
        ("testDecoderSimple", testDecoderSimple),
        ("testEventFromJSON", testEventFromJSON),
    ]
}

extension S3Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__S3Tests = [
        ("testSimpleEventFromJSON", testSimpleEventFromJSON),
    ]
}

extension SESTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SESTests = [
        ("testSimpleEventFromJSON", testSimpleEventFromJSON),
    ]
}

extension SNSTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SNSTests = [
        ("testSimpleEventFromJSON", testSimpleEventFromJSON),
    ]
}

extension SQSTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SQSTests = [
        ("testSimpleEventFromJSON", testSimpleEventFromJSON),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ALBTests.__allTests__ALBTests),
        testCase(APIGatewayTests.__allTests__APIGatewayTests),
        testCase(APIGatewayV2Tests.__allTests__APIGatewayV2Tests),
        testCase(Base64Tests.__allTests__Base64Tests),
        testCase(CloudwatchTests.__allTests__CloudwatchTests),
        testCase(DateWrapperTests.__allTests__DateWrapperTests),
        testCase(DynamoDBTests.__allTests__DynamoDBTests),
        testCase(S3Tests.__allTests__S3Tests),
        testCase(SESTests.__allTests__SESTests),
        testCase(SNSTests.__allTests__SNSTests),
        testCase(SQSTests.__allTests__SQSTests),
    ]
}
#endif
